version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: benchmarks
          command: |
            echo "Checkout observatorium/deployments"
            cd ../ && git clone https://github.com/observatorium/deployments.git
            cd loki-benchmarks && make bench-dev
            cp ./benchmarks/junit.xml /tmp/test-results/
      - store_test_results:
          path: /tmp/test-results
