version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15-rc-buster
    working_directory: /go/src/github.com/obervatorium/loki-benchmarks
    steps:
      - checkout
      - run:
          name: benchmarks
          command: |
            echo "Checkout observatorium/deployments"
            cd ../ && git clone https://github.com/observatorium/deployments.git
            make bench-env
            cp ./benchmarks/junit.xml /tmp/test-results/
      - store_test_results:
          path: /tmp/test-results
