version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/loki-benchmarks
    steps:
      - checkout
      - run:
          name: benchmarks
          command: |
            echo "Checkout observatorium/deployments"
            cd ../ && git clone https://github.com/observatorium/deployments.git
            cd loki-benchmarks && make bench-dev
      - store_test_results:
          path: benchmarks
