global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'loki-query-frontend'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:3100']
  - job_name: 'loki-distributor'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:3101']
  - job_name: 'loki-ingester'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:3102']
  - job_name: 'loki-querier'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:3103']
