logger:
  name: logger
  namespace: default
  image: quay.io/periklis/logger:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: default
  image: docker.io/curlimages/curl:7.72.0
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend

loki:
  distributor: http://observatorium-xyz-loki-distributor-http.observatorium.svc.cluster.local:3100
  queryFrontend: http://observatorium-xyz-loki-query-frontend-http.observatorium.svc.cluster.local:3100

scenarios:
  highVolumeReads:
    enabled: true
    samples:
      interval: "30s"
      range: "300s"
      total: 10
    writers:
      replicas: 10
      throughput: 100
    readers:
      replicas: 2
      query: 'query=sum(rate({component!=""}[1h])) by (level)'
      startThreshold: 1024000
  highVolumeWrites:
    enabled: true
    samples:
      interval: "30s"
      range: "300s"
      total: 10
    writers:
      replicas: 10
      throughput: 100
